# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
  displayName: Publish
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/mywebsite'
    ArtifactName: 'mywebsite'
    publishLocation: 'Container'


- script: |
    echo "Installing Terraform"
    curl -sL https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_amd64.zip -o terraform.zip
    unzip terraform.zip
    sudo mv terraform /usr/local/bin/
    terraform version
  displayName: 'Install Terraform'

- script: |
    echo "Initializing Terraform"
    terraform init -backend-config="storage_account_name=$(terraformstate112)" -backend-config="container_name=$(terraformstate)" -backend-config="access_key=$(sp=r&st=2023-11-03T20:12:26Z&se=2023-11-04T04:12:26Z&spr=https&sv=2022-11-02&sr=c&sig=q9SnJH%2FfqEWiLAp7Kf3ob3lNsoXHVk3wv0xUumuKpr4%3D)" -backend-config="key=terraform.tfstate"
  displayName: 'Initialize Terraform'
  env:
    BackendStorageAccountName: 'terraformstate112'
    BackendContainerName: 'terraformstate'
    BackendAccessKey: $(sp=r&st=2023-11-03T20:12:26Z&se=2023-11-04T04:12:26Z&spr=https&sv=2022-11-02&sr=c&sig=q9SnJH%2FfqEWiLAp7Kf3ob3lNsoXHVk3wv0xUumuKpr4%3D)

- script: |
    echo "Creating Terraform Plan"
    terraform plan -out=tfplan
  displayName: 'Create Terraform Plan'

- script: |
    echo "Applying Terraform Plan"
    terraform apply -auto-approve tfplan
  displayName: 'Apply Terraform Plan'
