# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- script: ls $(Build.ArtifactStagingDirectory)
  displayName: 'List Artifacts'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'WebApplication1'
    publishLocation: 'Container'


- script: |
    echo "Installing Terraform"
    choco install terraform --version 1.1.0
    terraform version
  displayName: 'Install Terraform'
  continueOnError: false

- script: |
    echo "Initializing Terraform"
    terraform init -backend-config="storage_account_name=$(terraformstate112)" -backend-config="container_name=$(terraformstate)" -backend-config="access_key=$(sp=r&st=2023-11-03T20:12:26Z&se=2023-11-04T04:12:26Z&spr=https&sv=2022-11-02&sr=c&sig=q9SnJH%2FfqEWiLAp7Kf3ob3lNsoXHVk3wv0xUumuKpr4%3D)" -backend-config="key=terraform.tfstate"
  displayName: 'Initialize Terraform'
  env:
    BackendStorageAccountName: 'terraformstate'
    BackendContainerName: 'terraformstate'
    BackendAccessKey: $(sp=r&st=2023-11-03T20:12:26Z&se=2023-11-04T04:12:26Z&spr=https&sv=2022-11-02&sr=c&sig=q9SnJH%2FfqEWiLAp7Kf3ob3lNsoXHVk3wv0xUumuKpr4%3D)

- script: |
    az login --service-principal -u "$(clientId)" -p "$(clientSecret)"  --tenant "$(tenant)"
    az storage blob download --container-name "terraformstate" --name "newmain.tf" --file "newmain.tf" --account-name "terraformstate112"
  displayName: 'Download Nested Terraform Template from Blob Storage'
  env:
    clientId: $(62ba6d2f-4192-4cf5-a00d-42328f7d7dfd)
    clientSecret: $(nJP8Q~_EqLNHRP2WxOe.b1HjVrKytOXVprvW1ca9)
    tenant: "$(04e77d4-81e7-4c16-ab44-935220bed6dd)"
    

- script: |
    echo "Creating Terraform Plan"
    terraform plan -out=tfplan
  displayName: 'Create Terraform Plan'

- script: |
    echo "Applying Terraform Plan"
    terraform apply -auto-approve tfplan
  displayName: 'Apply Terraform Plan'
